### ISSUE TITLE
maven build failure with documentation project

### ISSUE THREAD

**Issue by prem82** [rackerlabs/atom-hopper#293]
I simply cloned the repo to my local windows machine and executed the below command.

> mvn clean install

I get the below error. Could you please let me know, if I am missing something?

[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building ATOM Hopper - Documentation 1.2.34-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- clouddocs-maven-plugin:1.6.1:generate-webhelp (doc) @ documentation ---
[INFO] Processing input file: ah-intro.xml
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] ATOM Hopper - ATOMpub Server Collection ............ SUCCESS [  0.365 s]
[INFO] ATOM Hopper - Test Utility ......................... SUCCESS [  1.519 s]
[INFO] ATOM Hopper - ATOMpub Server Framework ............. SUCCESS [  3.799 s]
[INFO] ATOM Hopper - Hibernate Adapter .................... SUCCESS [  2.560 s]
[INFO] ATOM Hopper - MongoDB Adapter ...................... SUCCESS [  2.026 s]
[INFO] ATOM Hopper - Postgres Adapter ..................... SUCCESS [  1.695 s]
[INFO] ATOM Hopper - Default Jetty Server ................. SUCCESS [ 11.714 s]
[INFO] ATOM Hopper - Migration Adapter .................... SUCCESS [  1.438 s]
[INFO] ATOM Hopper - JDBC Adapter ......................... SUCCESS [  2.185 s]
[INFO] ATOM Hopper - AtomHopper-WAR-RPM-DEB ............... SUCCESS [  3.751 s]
[INFO] ATOM Hopper - ATOMpub Server Framework Testing Suite SUCCESS [ 10.800 s]
[INFO] ATOM Hopper - Documentation ........................ FAILURE [  2.247 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.383 s
[INFO] Finished at: 2015-12-04T12:35:46+05:30
[INFO] Final Memory: 33M/382M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.rackspace.cloud.api:clouddocs-maven-plugin:1.6.1:generate-webhelp (doc) on project documentation: Execution doc of goal com.rackspace.cloud.api:clouddocs-maven-plugin:1.6.1:generate-webhelp failed: **String index out of range: -1 -> [Help 1]**

**Comment by usnavi** [comment]
Hi,

None of us have windows machines, so we might be unaware of a specific issue.

What is the output of mvn -version?
Is there more info when you run mvn -X clean install?

We are running with:

Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 07:51:28-0600)
Maven home: /Users/rona6028/apps/apache-maven-3.0.5
Java version: 1.7.0_67, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.9.5", arch: "x86_64", family: "mac"

Let me know what you see,

Greg

**Comment by prem82** [comment]
Hi Greg - Here is the output from mvn -X clean install. It does not give any additional information.

[mvn-output.txt](https://github.com/rackerlabs/atom-hopper/files/52949/mvn-output.txt)

We are using windows machines and would like to try atom-hopper. Other than the file paths - is there any specific changes that needs to be done to the source to make it work on windows?.

I have not gone through the code yet. Just curious to know.

**Comment by prem82** [comment]
Build is successful when ran from a Ubuntu machine. Any plans to port this to windows pls?

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ATOM Hopper - ATOMpub Server Collection ........... SUCCESS [39.607s]
[INFO] ATOM Hopper - Test Utility ........................ SUCCESS [1:37.313s]
[INFO] ATOM Hopper - ATOMpub Server Framework ............ SUCCESS [4:30.120s]
[INFO] ATOM Hopper - Hibernate Adapter ................... SUCCESS [23.162s]
[INFO] ATOM Hopper - MongoDB Adapter ..................... SUCCESS [4:44.882s]
[INFO] ATOM Hopper - Postgres Adapter .................... SUCCESS [18.844s]
[INFO] ATOM Hopper - Default Jetty Server ................ SUCCESS [1:25.993s]
[INFO] ATOM Hopper - Migration Adapter ................... SUCCESS [6.481s]
[INFO] ATOM Hopper - JDBC Adapter ........................ SUCCESS [31.646s]
[INFO] ATOM Hopper - AtomHopper-WAR-RPM-DEB .............. SUCCESS [36.925s]
[INFO] ATOM Hopper - ATOMpub Server Framework Testing Suite  SUCCESS [57.180s]
[INFO] ATOM Hopper - Documentation ....................... SUCCESS [12:08.555s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28:01.623s
[INFO] Finished at: Sun Dec 06 02:09:42 IST 2015
[INFO] Final Memory: 43M/219M
[INFO] ------------------------------------------------------------------------

**Comment by usnavi** [comment]
Hi Premkumar,

We can definitely accept pull requests to support windows, but our team doesn't have immediate access to windows boxes at the moment.  Not a high priority as most people run it on Linux.

That said, I wouldn't be surprised if the failure comes from a hardcoded "/" in a file path, which is an easy fix.

Greg

**Comment by prem82** [comment]
Great. We deployed the app directly in Linux servers. 
One question - how do we access the service document in atom hopper?. What is the url for that?.
I remember I get the service document in the root (using abdera directly).
