### ISSUE TITLE
Context Root is not detected in the individual entry URLs

### ISSUE THREAD

**Issue by prem82** [rackerlabs/atom-hopper#294]
Hi Team - I deployed Atom war ver 1.2.33 on to an tomcat instance, under the context root "atom". Here is the URL. 

http://ec2-52-77-209-214.ap-southeast-1.compute.amazonaws.com:8080/atom/tracking/gmo

The feed URLs are updated with the context root "atom", but the individual entry URLs are not.

**feed url:**

http://ec2-52-77-209-214.ap-southeast-1.compute.amazonaws.com:8080/atom/tracking/gmo/

**entry url:**

http://ec2-52-77-209-214.ap-southeast-1.compute.amazonaws.com:8080/tracking/gmo/entries/urn:uuid:f95d3200-bee0-4e36-a949-19f92518e3a5

Is this a bug or am I missing any configurations?

**Comment by usnavi** [comment]
Are you missing the `atom` slug in your entry url?  E.g., http://ec2-52-77-209-214.ap-southeast-1.compute.amazonaws.com:8080/atom/tracking/gmo/entries/urn:uuid:f95d3200-bee0-4e36-a949-19f92518e3a5

**Comment by prem82** [comment]
Yes Grey. Could you please help me fix this.?

**Comment by usnavi** [comment]
Can you show me 1 entry from your feed?  So are you saying that the atom entry link doesn't have the atom slug?

**Comment by prem82** [comment]
Pls click the below link...  This feed has few entries...

http://ec2-52-77-209-214.ap-southeast-1.compute.amazonaws.com:8080/atom/tracking/gmo/

Thanks,
Prem

**Comment by usnavi** [comment]
I get a connection refused... :-(

**Comment by prem82** [comment]
Oh.  I am able to access it...
Here is the complete feed with three entries...

<feed xmlns="http://www.w3.org/2005/Atom"><link href="
http://ec2-52-77-209-214.ap-southeast-1.compute.amazonaws.com:8080/atom/tracking/gmo/"
rel="current" /><link href="
http://ec2-52-77-209-214.ap-southeast-1.compute.amazonaws.com:8080/atom/tracking/gmo/"
rel="self" /><id>urn:uuid:80b48cfd-a061-4ed0-9c00-27338b38af18</id><title
type="text">tracking/gmo</title><link href="
http://ec2-52-77-209-214.ap-southeast-1.compute.amazonaws.com:8080/atom/tracking/gmo/?marker=urn:uuid:f95d3200-bee0-4e36-a949-19f92518e3a5&amp;limit=25&amp;search=&amp;direction=forward"
rel="previous" /><link href="
http://ec2-52-77-209-214.ap-southeast-1.compute.amazonaws.com:8080/atom/tracking/gmo/?marker=urn:uuid:f95d3200-bee0-4e36-a949-19f92518e3a5&amp;limit=25&amp;search=&amp;direction=backward"
rel="last" /><updated>2015-12-18T21:08:19.029Z</updated><entry
xmlns:tracking="http://www.tesco.com/tracking">
<tracking:trackingid>trackingid001</tracking:trackingid>
<tracking:orderid>orderid001</tracking:orderid>
<tracking:status>DISPATCHED</tracking:status>
<tracking:statusdescription>Parcel is dispatched from
warehouse</tracking:statusdescription>
<tracking:time>2015-12-16T12:20:00.335Z</tracking:time>
<tracking:agent>Oakwood</tracking:agent> <tracking:location>On the
road</tracking:location><id>urn:uuid:f95d3200-bee0-4e36-a949-19f92518e3a5</id><link
href="
http://ec2-52-77-209-214.ap-southeast-1.compute.amazonaws.com:8080/tracking/gmo/entries/urn:uuid:f95d3200-bee0-4e36-a949-19f92518e3a5"
rel="self"
/><updated>2015-12-17T13:20:40.643Z</updated><published>2015-12-17T13:20:40.643Z</published></entry><entry
xmlns:tracking="http://www.tesco.com/tracking">
<tracking:trackingid>trackingid001</tracking:trackingid>
<tracking:orderid>orderid001</tracking:orderid>
<tracking:status>DISPATCHED</tracking:status>
<tracking:statusdescription>Parcel is dispatched from
warehouse</tracking:statusdescription>
<tracking:time>2015-12-16T12:20:00.335Z</tracking:time>
<tracking:agent>Oakwood</tracking:agent> <tracking:location>On the
road</tracking:location><id>urn:uuid:45d4d81d-998d-4156-b970-29e148f75227</id><link
href="
http://ec2-52-77-209-214.ap-southeast-1.compute.amazonaws.com:8080/tracking/gmo/entries/urn:uuid:45d4d81d-998d-4156-b970-29e148f75227"
rel="self"
/><updated>2015-12-17T13:20:39.761Z</updated><published>2015-12-17T13:20:39.761Z</published></entry><entry
xmlns:tracking="http://www.tesco.com/tracking">
<tracking:trackingid>trackingid001</tracking:trackingid>
<tracking:orderid>orderid001</tracking:orderid>
<tracking:status>DISPATCHED</tracking:status>
<tracking:statusdescription>Parcel is dispatched from
warehouse</tracking:statusdescription>
<tracking:time>2015-12-16T12:20:00.335Z</tracking:time>
<tracking:agent>Oakwood</tracking:agent> <tracking:location>On the
road</tracking:location><id>urn:uuid:b6c6ad7d-330f-4698-b6db-23b926951b85</id><link
href="
http://ec2-52-77-209-214.ap-southeast-1.compute.amazonaws.com:8080/tracking/gmo/entries/urn:uuid:b6c6ad7d-330f-4698-b6db-23b926951b85"
rel="self"
/><updated>2015-12-17T13:20:38.491Z</updated><published>2015-12-17T13:20:38.491Z</published></entry></feed>

Thanks,
Prem

**Comment by prem82** [comment]
Hi - Were you able to check this issue?

**Comment by prem82** [comment]
The self referencing links works perfectly fine with MongoDB adapters. The issue exists with H2 DB. I switched to mongo db.
